### ISSUE TITLE
Home (Katie Reynolds, Epic)

### ISSUE THREAD

**Issue by ig-feedback** [ahdis/ch-elm#53]
ch.fhir.ig.ch-elm#1.0.0 /

Some general feedback from Epic:

-The specification is clearly written. The definition of MustSupport is excellent - refreshingly simple to understand compared to many other implementation guides. We're also interested to see the use of imposeProfile, as this is a relatively new concept and few other implementation guides use it yet.
-The main concern we have is with complexity, and therefore difficulty of implementation. 
  For example:
      -Varying name format by organism type.
            -This is rare in a FHIR specification, and will require work from vendors and/or 
              laboratory organizations to develop.
            -In some cases in other countries, we've seen the use of a centralized middleware 
             layer to do some translation instead of having every implementer maintain this logic, 
             allowing implementers to use standard FHIR profiles.
      -Varying codeset by diagnosis.
            -This is complex and potentially requires workflow updates to ensure laboratory 
              users document the required information.
            -Could this information be sent as a standard DiagnosticReport (like the example of a 
             microbiology report at https://hl7.org/fhir/STU3/diagnosticreport-micro1.json.html, 
             or using the microbiology format with methods outlined in Epic's documentation at 
             https://fhir.epic.com/Specifications?api=998?)
-FHIR is seeing global success due to its implementation of REST with standard and reuseable healthcare resources and OAuth. This spec is trialing FHIR documents with bespoke FHIR resources using mTLS instead of OAuth. What's the reason for doing that, rather than using what has been successful elsewhere?

Katie Reynolds, Epic

**Comment by oliveregger** [comment]
> ch.fhir.ig.ch-elm#1.0.0 /
>
> Some general feedback from Epic:
> 
> -The specification is clearly written. The definition of MustSupport is excellent 
> - refreshingly simple to understand compared to many other implementation guides. We're also interested to see the use of imposeProfile, as this is a relatively new concept and few other implementation guides use it yet.

Thank you for the feedback!
 
>-The main concern we have is with complexity, and therefore difficulty of implementation. For example: 
>-Varying name format by organism type. 
>-This is rare in a FHIR specification, and will require work from vendors and/or laboratory organizations to develop. 
>-In some cases in other countries, we've seen the use of a centralized middleware layer to do some translation instead of having every implementer maintain this logic, allowing implementers to use standard FHIR profiles. 

That the name format is dependent by organism type is due to the regulation in Switzerland, which requires the different formats due to data protection. This could only be changed, if the regulation changes. A centralized middle-ware cannot be put in place for this project due to the same reasons.

>-Varying codeset by diagnosis. 
>-This is complex and potentially requires workflow updates to ensure laboratory users document the required information. 
>-Could this information be sent as a standard DiagnosticReport (like the example of a microbiology report at https://hl7.org/fhir/STU3/diagnosticreport-micro1.json.html, or using the microbiology format with methods outlined in Epic's documentation at https://fhir.epic.com/Specifications?api=998?) 

For the information to be provided we derived from the work happening in Europe with the [HL7 FHIR Lab report](https://hl7.eu/fhir/laboratory/) and harmonized with that work group.  The construct uses Observation resources as the basis, but we will follow  the future recommendations on the work which is done within the HL7 Europe Implementation Guide.

>-FHIR is seeing global success due to its implementation of REST with standard and reuseable healthcare resources and OAuth. This spec is trialing FHIR documents with bespoke FHIR resources using mTLS instead of OAuth. What's the reason for doing that, rather than using what has been successful elsewhere?

The exchange in that case is required to be a document, see also design choice discussion here: https://build.fhir.org/ig/hl7-eu/laboratory/#design-choiches. 

That mTLS was chosen over OAuth is an implementation requirement of the Ministry of Health in Switzerland (FOPH).

Please apologize the delayed response and hope the answers clarify your questions.
